# Generated by Django 2.1.3 on 2018-12-01 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('answer_time', models.DateTimeField(blank=True, null=True)),
                ('accepted', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lesson_id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('modification_time', models.DateTimeField(auto_now_add=True)),
                ('beginning_time', models.DateTimeField()),
                ('ending_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.IntegerField(choices=[(0, 'APPLICATION_CREATION'), (1, 'APPLICATION_ANSWER'), (2, 'LESSON_CREATION'), (3, 'DELETION_FROM_STUDENTS'), (4, 'LESSON_CHANGING'), (5, 'LESSON_DELETION')])),
                ('seen', models.BooleanField(default=False)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Application')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('experience', models.TextField(blank=True, max_length=4096, null=True)),
                ('education', models.TextField(blank=True, max_length=4096, null=True)),
                ('address', models.TextField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(blank=True, max_length=4096, null=True)),
                ('home_schooling', models.BooleanField(default=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('distance_learning', models.BooleanField(default=False)),
                ('ege', models.BooleanField(default=False)),
                ('oge', models.BooleanField(default=False)),
                ('foreign_lang_cert', models.BooleanField(default=False)),
                ('primary_school', models.BooleanField(default=False)),
                ('secondary_school', models.BooleanField(default=False)),
                ('olympiads', models.BooleanField(default=False)),
                ('university', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('ball', models.IntegerField()),
                ('text', models.TextField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('vacancy_id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subject', models.CharField(max_length=128)),
                ('ege', models.BooleanField(default=False)),
                ('oge', models.BooleanField(default=False)),
                ('foreign_lang_cert', models.BooleanField(default=False)),
                ('primary_school', models.BooleanField(default=False)),
                ('secondary_school', models.BooleanField(default=False)),
                ('olympiads', models.BooleanField(default=False)),
                ('university', models.BooleanField(default=False)),
                ('home_schooling', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('extra_info', models.TextField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('tutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='students_tutor', serialize=False, to='backend.Profile')),
                ('students', models.ManyToManyField(to='backend.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='vacancy',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_owner', to='backend.Profile'),
        ),
        migrations.AddField(
            model_name='report',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_author', to='backend.Profile'),
        ),
        migrations.AddField(
            model_name='report',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_recipient', to='backend.Profile'),
        ),
        migrations.AddField(
            model_name='notification',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_profile', to='backend.Profile'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_student', to='backend.Profile'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_tutor', to='backend.Profile'),
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_student', to='backend.Profile'),
        ),
        migrations.AddField(
            model_name='application',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_vacancy', to='backend.Vacancy'),
        ),
    ]
