# Generated by Django 2.1.3 on 2018-12-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='vk_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
