# Generated by Django 2.1.1 on 2018-10-10 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20181010_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='beginning_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='ending_time',
            field=models.TimeField(null=True),
        ),
    ]
