# Generated by Django 2.1.7 on 2019-02-20 00:10

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='beginning_time',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2019, 2, 20, 0, 10, 35, 614147, tzinfo=utc))]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.DurationField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.timedelta(0, 1800)), django.core.validators.MaxValueValidator(limit_value=datetime.timedelta(0, 14400))]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=10000)]),
        ),
    ]
