# Generated by Django 2.1.7 on 2019-02-20 01:24

from django.db import migrations, models
import lessons.validators


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20190220_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='beginning_time',
            field=models.DateTimeField(validators=[lessons.validators.validate_beginning_time]),
        ),
    ]
