# Generated by Django 2.1.7 on 2019-02-22 23:24

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import lessons.validators


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_auto_20190220_0124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('-id',), 'verbose_name': 'lesson', 'verbose_name_plural': 'lessons'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='beginning_time',
            field=models.DateTimeField(validators=[lessons.validators.validate_beginning_time], verbose_name='beginning time'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.DurationField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.timedelta(0, 1800)), django.core.validators.MaxValueValidator(limit_value=datetime.timedelta(0, 14400))], verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='ending_time',
            field=models.DateTimeField(editable=False, verbose_name='ending time'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='modification_time',
            field=models.DateTimeField(editable=False, verbose_name='modification time'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=10000)], verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_student', to=settings.AUTH_USER_MODEL, verbose_name='student'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_tutor', to=settings.AUTH_USER_MODEL, verbose_name='tutor'),
        ),
    ]
