# Generated by Django 2.2a1 on 2019-02-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20190210_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(max_length=32),
        ),
    ]
