FROM node:alpine

RUN mkdir -p /opt/services/tutors-frontend
WORKDIR /opt/services/tutors-frontend

COPY package.json package-lock.json /opt/services/tutors-frontend/
RUN npm install --silent

COPY . /opt/services/tutors-frontend/
RUN npm run build
