FROM node:alpine as builder

RUN mkdir -p /opt/services/tutors-frontend
WORKDIR /opt/services/tutors-frontend

COPY package.json package-lock.json ./
RUN npm install --silent

RUN rm -rf build
COPY . ./
RUN npm run build
