FROM node:alpine as builder

RUN mkdir -p /opt/services/tutors-frontend
WORKDIR /opt/services/tutors-frontend

COPY package.json package-lock.json ./
RUN npm install --silent

COPY . ./
RUN npm run build

FROM nginx:alpine

WORKDIR /var/www/tutors-frontend
COPY --from=builder /opt/services/tutors-frontend ./