version: "3"

services:
  backend:
    container_name: backend
    restart: always
    build: ./backend/
    volumes:
      - backend-staticfiles:/opt/services/backend/staticfiles
      - backend-media:/opt/services/backend/media
    command: ["sh", "./entrypoint.sh"]
    expose: 
      - "8000"
    depends_on:
      - postgres

  vk-apps-frontend:
    container_name: vk-apps-frontend
    build: vk-apps-frontend/
    volumes:
      - vk-apps-frontend-build:/opt/services/vk-apps-frontend/build

  nginx:
    container_name: nginx
    restart: always
    build: ./docker/nginx/
    ports:
      - 80:80
    volumes:
      - backend-staticfiles:/var/www/backend/staticfiles
      - backend-media:/var/www/backend/media
      - vk-apps-frontend-build:/var/www/vk-apps-frontend
    depends_on: 
      - backend
      - vk-apps-frontend

  postgres:
    container_name: postgres
    restart: always
    image: postgres:alpine
    volumes:
      - postgres-config:/etc/postgresql
      - postgres-log:/var/log/postgresql
      - postgres-db:/var/lib/postgresql
    expose: 
      - "5432"
    env_file: .env

volumes:
  backend-staticfiles:
  backend-media:
  vk-apps-frontend-build:
  postgres-config:
  postgres-log:
  postgres-db:
