version: "3"

services:
  nginx:
    restart: always
    build: 
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - vk-apps-frontend-build:/opt/services/vk-apps-frontend/build
      - backend-media:/opt/services/backend/media
      - backend-staticfiles:/opt/services/backend/staticfiles
      - backend-socket:/opt/services/backend/socket
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.crt:/etc/nginx/ssl/nginx.crt
      - ./docker/nginx/nginx.key:/etc/nginx/ssl/nginx.key
    ports:
      - "443:443"
      - "80:80"
    depends_on: 
      - backend

  postgres:
    image: postgres:alpine
    restart: always
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    expose: 
      - "5432"
    env_file: docker/.env

  redis:
    image: redis:alpine
    restart: always
    expose:
      - "6379"

  backend:
    container_name: backend
    restart: always
    build: ./backend/
    volumes:
      - backend-media:/backend/media
      - backend-staticfiles:/backend/staticfiles
      - backend-socket:/backend/socket
    expose: 
      - "8000"
    depends_on:
      - postgres
      - redis

volumes:
  backend-media:
  backend-staticfiles:
  backend-socket:
  vk-apps-frontend-build:
  postgres-volume:
