version: "3"

services:
  tutors-backend:
    restart: always
    container_name: tutors-backend
    build: ./backend/
    volumes:
      - tutors-backend:/opt/services/tutors-backend/staticfiles
    command: sh entrypoint.sh
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - postgresql

  tutors-frontend:
    image: node:latest
    container_name: tutors-frontend
    build: ./frontend/
    volumes: 
      - tutors-frontend:/opt/services/tutors-frontend/build

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - 80:80
    volumes: 
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - tutors-backend:/var/www/tutors-backend/staticfiles
      - tutors-frontend:/var/www/tutors-frontend/
    depends_on: 
      - tutors-backend
      - tutors-frontend

  postgresql:
    restart: always
    ports:
      - 5432:5432
    image: postgres:latest
    volumes:
      - ./docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    env_file: .env

volumes:
  tutors-backend:
  tutors-frontend:
