version: "3"

services:
  tutors-backend-dev:
    container_name: tutors-backend-dev
    build: ./backend/
    volumes:
      - tutors-backend-dev:/opt/services/tutors-backend/staticfiles
    command: ["sh", "./entrypoint.sh"]
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - postgresql-dev

  tutors-frontend-dev:
    container_name: tutors-frontend-dev
    build: ./frontend/
    volumes: 
      - tutors-frontend-dev:/opt/services/tutors-frontend/build
    ports:
      - 3000:3000
    env_file: .env

  tutors-nginx-dev:
    container_name: tutors-nginx-dev
    image: nginx:latest
    ports:
      - 80:80
    volumes: 
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - tutors-backend-dev:/var/www/tutors-backend/staticfiles
      - tutors-frontend-dev:/var/www/tutors-frontend/
    depends_on: 
      - tutors-backend-dev
      - tutors-frontend-dev

  postgresql-dev:
    container_name: postgresql-dev
    image: postgres:latest
    volumes:
      - postgres-config-dev:/etc/postgresql
      - postgres-log-dev:/var/log/postgresql
      - postgres-db-dev:/var/lib/postgresql
    ports:
      - 5432:5432
    env_file: .env

volumes:
  tutors-backend-dev:
  tutors-frontend-dev:
  postgres-config-dev:
  postgres-log-dev:
  postgres-db-dev:
