version: "3"

services:
  tutors-backend:
    restart: always
    container_name: tutors-backend
    build: ./backend/
    volumes:
      - ./backend/staticfiles:/opt/services/tutors-backend/staticfiles
    command: ["sh", "./entrypoint.prod.sh"]
    expose: 
      - "8000"
    env_file: .env
    depends_on:
      - postgresql

  tutors-frontend:
    container_name: tutors-frontend
    build: 
      context: ./frontend/
      dockerfile: Dockerfile.prod
    volumes:
      - ./frontend/build:/opt/services/tutors-frontend/build
    env_file: .env

  tutors-nginx:
    container_name: tutors-nginx
    restart: always
    build: ./docker/nginx/
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./backend/staticfiles:/var/www/tutors-backend/staticfiles
      - ./frontend/build:/var/www/tutors-frontend
    env_file: .env
    depends_on: 
      - tutors-backend
      - tutors-frontend

  postgresql:
    container_name: tutors-postgres
    restart: always
    image: postgres:alpine
    volumes:
      - postgres-config:/etc/postgresql
      - postgres-log:/var/log/postgresql
      - postgres-db:/var/lib/postgresql
    expose: 
      - "5432"
    env_file: .env

volumes:
  postgres-config:
  postgres-log:
  postgres-db:
