version: "3"

services:
  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./vk-apps-frontend/build:/opt/services/vk-apps-frontend/build
      - backend-volume:/opt/services/backend/
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.crt:/etc/nginx/ssl/nginx.crt
      - ./docker/nginx/nginx.key:/etc/nginx/ssl/nginx.key
    ports:
      - "443:443"
      - "80:80"
    depends_on: 
      - backend

  postgres:
    image: postgres:alpine
    restart: always
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    expose: 
      - "5432"
    env_file: .env

  redis:
    image: redis:alpine
    restart: always
    expose:
      - "6379"

  backend:
    container_name: backend
    restart: always
    build: ./backend/
    volumes:
      - backend-volume:/backend
    expose: 
      - "8000"
    depends_on:
      - postgres
      - redis

volumes:
  backend-volume:
  postgres-volume:
