version: "3"

services:
  tutors-backend:
    restart: always
    container_name: tutors-backend
    build: ./backend/
    volumes:
      - tutors-backend:/opt/services/tutors-backend/staticfiles
    command: ["sh", "./entrypoint-production.sh"]
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - postgresql

  tutors-frontend:
    container_name: tutors-frontend
    build: 
      context: ./frontend/
      dockerfile: Dockerfile-production
    volumes:
      - tutors-frontend:/opt/services/tutors-frontend/build

  tutors-nginx:
    restart: always
    image: nginx:latest
    ports:
      - 443:443
    volumes: 
      - ./docker/nginx/nginx-production.conf:/etc/nginx/conf.d
      - ./nginx.crt:/etc/nginx/ssl/nginx.crt
      - ./nginx.key:/etc/nginx/ssl/nginx.key
      - tutors-backend:/var/www/tutors-backend/staticfiles
      - tutors-frontend:/var/www/tutors-frontend/
    depends_on: 
      - tutors-backend
      - tutors-frontend

  postgresql:
    restart: always
    image: postgres:latest
    volumes:
      - postgres-config:/etc/postgresql
      - postgres-log:/var/log/postgresql
      - postgres-db:/var/lib/postgresql
    ports:
      - 5432:5432
    env_file: .env

volumes:
  tutors-backend:
  tutors-frontend:
  postgres-config:
  postgres-log:
  postgres-db:
