const VK_API_STOP_FETCHING = 'VK/VK_API_STOP_FETCHING';

const VK_API_USERS_GET_REQUEST = 'VK/VK_API_USERS_GET_REQUEST';
const VK_API_USERS_GET_FETCHED = 'VK/VK_API_USERS_GET_FETCHED';
const VK_API_USERS_GET_FAILED = 'VK/VK_API_USERS_GET_FAILED';

const VK_API_NOTIFICATION_STATUS_REQUEST = 'VK/VK_API_NOTIFICATION_STATUS_REQUEST';
const VK_API_NOTIFICATION_STATUS_FETCHED = 'VK/VK_API_NOTIFICATION_STATUS_FETCHED';
const VK_API_NOTIFICATION_STATUS_FAILED = 'VK/VK_API_NOTIFICATION_STATUS_FAILED';

export const apiConstants = {
  VK_API_STOP_FETCHING,

  VK_API_USERS_GET_REQUEST,
  VK_API_USERS_GET_FETCHED,
  VK_API_USERS_GET_FAILED,

  VK_API_NOTIFICATION_STATUS_REQUEST,
  VK_API_NOTIFICATION_STATUS_FETCHED,
  VK_API_NOTIFICATION_STATUS_FAILED,
};
