const VK_INIT = 'vk/VK_INIT';

const VK_ALLOW_NOTIFICATIONS_REQUEST = 'vk/VK_ALLOW_NOTIFICATIONS_REQUEST';
const VK_ALLOW_NOTIFICATIONS_SUCCESS = 'vk/VK_ALLOW_NOTIFICATIONS_SUCCESS';
const VK_ALLOW_NOTIFICATIONS_FAILURE = 'vk/VK_ALLOW_NOTIFICATIONS_FAILURE';

const VK_DENY_NOTIFICATIONS_REQUEST = 'vk/VK_DENY_NOTIFICATIONS_REQUEST';
const VK_DENY_NOTIFICATIONS_SUCCESS = 'vk/VK_DENY_NOTIFICATIONS_SUCCESS';
const VK_DENY_NOTIFICATIONS_FAILURE = 'vk/VK_DENY_NOTIFICATIONS_FAILURE';

const VK_GET_USER_INFO_REQUEST = 'vk/VK_GET_USER_INFO_REQUEST';
const VK_GET_USER_INFO_FETCHED = 'vk/VK_GET_USER_INFO_FETCHED';
const VK_GET_USER_INFO_FAILED = 'vk/VK_GET_USER_INFO_FAILED';

const VK_GET_ACCESS_TOKEN_REQUEST = 'vk/VK_GET_ACCESS_TOKEN_REQUEST';
const VK_GET_ACCESS_TOKEN_FETCHED = 'vk/VK_GET_ACCESS_TOKEN_FETCHED';
const VK_GET_ACCESS_TOKEN_FAILED = 'vk/VK_GET_ACCESS_TOKEN_FAILED';

export const appsConstants = {
  VK_INIT,
  VK_ALLOW_NOTIFICATIONS_REQUEST, VK_ALLOW_NOTIFICATIONS_SUCCESS, VK_ALLOW_NOTIFICATIONS_FAILURE,
  VK_DENY_NOTIFICATIONS_REQUEST, VK_DENY_NOTIFICATIONS_SUCCESS, VK_DENY_NOTIFICATIONS_FAILURE,
  VK_GET_USER_INFO_REQUEST, VK_GET_USER_INFO_FETCHED, VK_GET_USER_INFO_FAILED,
  VK_GET_ACCESS_TOKEN_REQUEST, VK_GET_ACCESS_TOKEN_FETCHED, VK_GET_ACCESS_TOKEN_FAILED,
};
