const VK_INIT = 'VK/VK_INIT';

const VK_ALLOW_NOTIFICATIONS_REQUEST = 'VK/VK_ALLOW_NOTIFICATIONS_REQUEST';
const VK_ALLOW_NOTIFICATIONS_SUCCESS = 'VK/VK_ALLOW_NOTIFICATIONS_SUCCESS';
const VK_ALLOW_NOTIFICATIONS_FAILURE = 'VK/VK_ALLOW_NOTIFICATIONS_FAILURE';

const VK_DENY_NOTIFICATIONS_REQUEST = 'VK/VK_DENY_NOTIFICATIONS_REQUEST';
const VK_DENY_NOTIFICATIONS_SUCCESS = 'VK/VK_DENY_NOTIFICATIONS_SUCCESS';
const VK_DENY_NOTIFICATIONS_FAILURE = 'VK/VK_DENY_NOTIFICATIONS_FAILURE';

const VK_GET_USER_INFO_REQUEST = 'VK/VK_GET_USER_INFO_REQUEST';
const VK_GET_USER_INFO_FETCHED = 'VK/VK_GET_USER_INFO_FETCHED';
const VK_GET_USER_INFO_FAILED = 'VK/VK_GET_USER_INFO_FAILED';

const VK_PAY_REQUEST = 'VK/VK_PAY_REQUEST';
const VK_PAY_SUCCESS = 'VK/VK_PAY_SUCCESS';
const VK_PAY_FAILURE = 'VK/VK_PAY_FAILURE';

export const appsConstants = {
  VK_INIT,

  VK_ALLOW_NOTIFICATIONS_REQUEST,
  VK_ALLOW_NOTIFICATIONS_SUCCESS,
  VK_ALLOW_NOTIFICATIONS_FAILURE,

  VK_DENY_NOTIFICATIONS_REQUEST,
  VK_DENY_NOTIFICATIONS_SUCCESS,
  VK_DENY_NOTIFICATIONS_FAILURE,

  VK_GET_USER_INFO_REQUEST,
  VK_GET_USER_INFO_FETCHED,
  VK_GET_USER_INFO_FAILED,

  VK_PAY_REQUEST,
  VK_PAY_SUCCESS,
  VK_PAY_FAILURE,
};