version: '3'

services:
  web:
    restart: always
    build: .
    expose:
      - "8000"
    depends_on:
      - postgresql
    env_file: .env
    volumes:
      - web:/data/web
    command: >
      bash -c "
      python manage.py migrate --noinput
      && gunicorn vktutor.wsgi:application -w 4 --bind 0.0.0.0:8000"

  nginx:
    restart: always
    build: ./docker/nginx/
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
    volumes:
      - web:/staticfiles
    depends_on:
      - web

  postgresql:
    restart: always
    image: postgres:latest
    volumes:
      - ./docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./backups/postgresql:/backup
    env_file: .env
    expose:
      - "5432"

  data:
    restart: always
    image: alpine
    volumes:
      - /var/lib/postgresql
    command: "true"

volumes:
  web:
