# Generated by Django 2.1.4 on 2019-01-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_apps_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkappsuser',
            name='vk_id',
            field=models.IntegerField(unique=True),
        ),
    ]
