# Generated by Django 2.2a1 on 2019-02-02 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vk_apps_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkappsuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vkappsuser',
            name='vk_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
