# Generated by Django 2.2a1 on 2019-02-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_apps_users', '0002_auto_20190202_0104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vkappsuser',
            options={'verbose_name': 'VK Apps User', 'verbose_name_plural': 'VK Apps Users'},
        ),
        migrations.AlterField(
            model_name='vkappsuser',
            name='vk_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='VK ID'),
        ),
    ]
