const GET_STUDENTS_REQUEST = 'api/GET_STUDENTS_REQUEST';
const GET_STUDENTS_SUCCESS = 'api/GET_STUDENTS_SUCCESS';
const GET_STUDENTS_FAILURE = 'api/GET_STUDENTS_FAILURE';

const DELETE_STUDENT_REQUEST = 'api/DELETE_STUDENT_REQUEST';
const DELETE_STUDENT_SUCCESS = 'api/DELETE_STUDENT_SUCCESS';
const DELETE_STUDENT_FAILURE = 'api/DELETE_STUDENT_FAILURE';

export const apiStudentsConstants = {
  GET_STUDENTS_REQUEST, GET_STUDENTS_SUCCESS, GET_STUDENTS_FAILURE,
  DELETE_STUDENT_REQUEST, DELETE_STUDENT_SUCCESS, DELETE_STUDENT_FAILURE,
};
