// export const apiConstants = {
//   CREATE_PROFILE_REQUEST, CREATE_PROFILE_SUCCESS, CREATE_PROFILE_FAILURE,
//   CREATE_VACANCY_REQUEST, CREATE_VACANCY_SUCCESS, CREATE_VACANCY_FAILURE,
//   ADD_SHEDULE_REQUEST, ADD_SHEDULE_SUCCESS, ADD_SHEDULE_FAILURE,
//   GET_PROFILE_REQUEST, GET_PROFILE_SUCCESS, GET_PROFILE_FAILURE,
//   SEARCH_VACANCY_REQUEST, SEARCH_VACANCY_SUCCESS, SEARCH_VACANCY_FAILURE,
//   GET_ACTIVE_VACANCIES_REQUEST, GET_ACTIVE_VACANCIES_SUCCESS, GET_ACTIVE_VACANCIES_FAILURE,
//   GET_STUDENTS_REQUEST, GET_STUDENTS_SUCCESS, GET_STUDENTS_FAILURE, 
//   DELETE_SCHEDULE_REQUEST, DELETE_SCHEDULE_SUCCESS, DELETE_SCHEDULE_FAILURE,
//   DELETE_VACANCY_REQUEST, DELETE_VACANCY_SUCCESS, DELETE_VACANCY_FAILURE,
//   DELETE_PROFILE_REQUEST, DELETE_PROFILE_SUCCESS, DELETE_PROFILE_FAILURE,
// };

// const CREATE_PROFILE_REQUEST = 'api/REGISTRATION_REQUEST';
// const CREATE_PROFILE_SUCCESS = 'api/REGISTRATION_SUCCESS';
// const CREATE_PROFILE_FAILURE = 'api/REGISTRATION_FAILURE';

// const CREATE_VACANCY_REQUEST = 'api/CREATE_VACANCY_REQUEST';
// const CREATE_VACANCY_SUCCESS = 'api/CREATE_VACANCY_SUCCESS';
// const CREATE_VACANCY_FAILURE = 'api/CREATE_VACANCY_FAILURE';

// const ADD_SHEDULE_REQUEST = 'api/ADD_SHEDULE_REQUEST';
// const ADD_SHEDULE_SUCCESS = 'api/ADD_SHEDULE_SUCCESS';
// const ADD_SHEDULE_FAILURE = 'api/ADD_SHEDULE_FAILURE';

// const GET_PROFILE_REQUEST = 'api/GET_PROFILE_REQUEST';
// const GET_PROFILE_SUCCESS = 'api/GET_PROFILE_SUCCESS';
// const GET_PROFILE_FAILURE = 'api/GET_PROFILE_FAILURE';

// const SEARCH_VACANCY_REQUEST = 'api/SEARCH_VACANCY_REQUEST';
// const SEARCH_VACANCY_SUCCESS = 'api/SEARCH_VACANCY_SUCCESS';
// const SEARCH_VACANCY_FAILURE = 'api/SEARCH_VACANCY_FAILURE';

// const GET_ACTIVE_VACANCIES_REQUEST = 'api/GET_ACTIVE_VACANCIES_REQUEST';
// const GET_ACTIVE_VACANCIES_SUCCESS = 'api/GET_ACTIVE_VACANCIES_SUCCESS';
// const GET_ACTIVE_VACANCIES_FAILURE = 'api/GET_ACTIVE_VACANCIES_FAILURE';

// const GET_STUDENTS_REQUEST = 'api/GET_STUDENTS_REQUEST';
// const GET_STUDENTS_SUCCESS = 'api/GET_STUDENTS_SUCCESS';
// const GET_STUDENTS_FAILURE = 'api/GET_STUDENTS_FAILURE';

// const DELETE_SCHEDULE_REQUEST = 'api/DELETE_SCHEDULE_REQUEST';
// const DELETE_SCHEDULE_SUCCESS = 'api/DELETE_SCHEDULE_SUCCESS';
// const DELETE_SCHEDULE_FAILURE = 'api/DELETE_SCHEDULE_FAILURE';

// const DELETE_VACANCY_REQUEST = 'api/DELETE_VACANCY_REQUEST';
// const DELETE_VACANCY_SUCCESS = 'api/DELETE_VACANCY_SUCCESS';
// const DELETE_VACANCY_FAILURE = 'api/DELETE_VACANCY_FAILURE';

// const DELETE_PROFILE_REQUEST = 'api/DELETE_PROFILE_REQUEST';
// const DELETE_PROFILE_SUCCESS = 'api/DELETE_PROFILE_SUCCESS';
// const DELETE_PROFILE_FAILURE = 'api/DELETE_PROFILE_FAILURE';

const API_REQUEST = 'api/API_REQUEST';
const API_SUCCESS = 'api/API_SUCCESS';
const API_FAILURE = 'api/API_FAILURE';

export const apiConstants = {
  API_REQUEST, API_SUCCESS, API_FAILURE
};