const CREATE_PROFILE_REQUEST = 'api/CREATE_PROFILE_REQUEST';
const CREATE_PROFILE_SUCCESS = 'api/CREATE_PROFILE_SUCCESS';
const CREATE_PROFILE_FAILURE = 'api/CREATE_PROFILE_FAILURE';

const CREATE_VACANCY_REQUEST = 'api/CREATE_VACANCY_REQUEST';
const CREATE_VACANCY_SUCCESS = 'api/CREATE_VACANCY_SUCCESS';
const CREATE_VACANCY_FAILURE = 'api/CREATE_VACANCY_FAILURE';

const ADD_LESSON_REQUEST = 'api/ADD_LESSON_REQUEST';
const ADD_LESSON_SUCCESS = 'api/ADD_LESSON_SUCCESS';
const ADD_LESSON_FAILURE = 'api/ADD_LESSON_FAILURE';

const GET_PROFILE_REQUEST = 'api/GET_PROFILE_REQUEST';
const GET_PROFILE_SUCCESS = 'api/GET_PROFILE_SUCCESS';
const GET_PROFILE_FAILURE = 'api/GET_PROFILE_FAILURE';

const SEARCH_VACANCY_REQUEST = 'api/SEARCH_VACANCY_REQUEST';
const SEARCH_VACANCY_SUCCESS = 'api/SEARCH_VACANCY_SUCCESS';
const SEARCH_VACANCY_FAILURE = 'api/SEARCH_VACANCY_FAILURE';

const GET_ACTIVE_VACANCIES_REQUEST = 'api/GET_ACTIVE_VACANCIES_REQUEST';
const GET_ACTIVE_VACANCIES_SUCCESS = 'api/GET_ACTIVE_VACANCIES_SUCCESS';
const GET_ACTIVE_VACANCIES_FAILURE = 'api/GET_ACTIVE_VACANCIES_FAILURE';

const GET_STUDENTS_REQUEST = 'api/GET_STUDENTS_REQUEST';
const GET_STUDENTS_SUCCESS = 'api/GET_STUDENTS_SUCCESS';
const GET_STUDENTS_FAILURE = 'api/GET_STUDENTS_FAILURE';

const DELETE_LESSON_REQUEST = 'api/DELETE_LESSON_REQUEST';
const DELETE_LESSON_SUCCESS = 'api/DELETE_LESSON_SUCCESS';
const DELETE_LESSON_FAILURE = 'api/DELETE_LESSON_FAILURE';

const DELETE_VACANCY_REQUEST = 'api/DELETE_VACANCY_REQUEST';
const DELETE_VACANCY_SUCCESS = 'api/DELETE_VACANCY_SUCCESS';
const DELETE_VACANCY_FAILURE = 'api/DELETE_VACANCY_FAILURE';

const DELETE_PROFILE_REQUEST = 'api/DELETE_PROFILE_REQUEST';
const DELETE_PROFILE_SUCCESS = 'api/DELETE_PROFILE_SUCCESS';
const DELETE_PROFILE_FAILURE = 'api/DELETE_PROFILE_FAILURE';

export const apiConstants = {
  CREATE_PROFILE_REQUEST, CREATE_PROFILE_SUCCESS, CREATE_PROFILE_FAILURE,
  CREATE_VACANCY_REQUEST, CREATE_VACANCY_SUCCESS, CREATE_VACANCY_FAILURE,
  ADD_LESSON_REQUEST, ADD_LESSON_SUCCESS, ADD_LESSON_FAILURE,
  GET_PROFILE_REQUEST, GET_PROFILE_SUCCESS, GET_PROFILE_FAILURE,
  SEARCH_VACANCY_REQUEST, SEARCH_VACANCY_SUCCESS, SEARCH_VACANCY_FAILURE,
  GET_ACTIVE_VACANCIES_REQUEST, GET_ACTIVE_VACANCIES_SUCCESS, GET_ACTIVE_VACANCIES_FAILURE,
  GET_STUDENTS_REQUEST, GET_STUDENTS_SUCCESS, GET_STUDENTS_FAILURE, 
  DELETE_LESSON_REQUEST, DELETE_LESSON_SUCCESS, DELETE_LESSON_FAILURE,
  DELETE_VACANCY_REQUEST, DELETE_VACANCY_SUCCESS, DELETE_VACANCY_FAILURE,
  DELETE_PROFILE_REQUEST, DELETE_PROFILE_SUCCESS, DELETE_PROFILE_FAILURE,
};