const CREATE_PROFILE_REQUEST = 'api/CREATE_PROFILE_REQUEST';
const CREATE_PROFILE_SUCCESS = 'api/CREATE_PROFILE_SUCCESS';
const CREATE_PROFILE_FAILURE = 'api/CREATE_PROFILE_FAILURE';

const CREATE_VACANCY_REQUEST = 'api/CREATE_VACANCY_REQUEST';
const CREATE_VACANCY_SUCCESS = 'api/CREATE_VACANCY_SUCCESS';
const CREATE_VACANCY_FAILURE = 'api/CREATE_VACANCY_FAILURE';

const GET_PROFILE_REQUEST = 'api/GET_PROFILE_REQUEST';
const GET_PROFILE_SUCCESS = 'api/GET_PROFILE_SUCCESS';
const GET_PROFILE_FAILURE = 'api/GET_PROFILE_FAILURE';

const UPDATE_PROFILE_REQUEST = 'api/UPDATE_PROFILE_REQUEST';
const UPDATE_PROFILE_SUCCESS = 'api/UPDATE_PROFILE_SUCCESS';
const UPDATE_PROFILE_FAILURE = 'api/UPDATE_PROFILE_FAILURE';

const SEARCH_VACANCIES_REQUEST = 'api/SEARCH_VACANCIES_REQUEST';
const SEARCH_VACANCIES_SUCCESS = 'api/SEARCH_VACANCIES_SUCCESS';
const SEARCH_VACANCIES_FAILURE = 'api/SEARCH_VACANCIES_FAILURE';

const GET_STUDENTS_REQUEST = 'api/GET_STUDENTS_REQUEST';
const GET_STUDENTS_SUCCESS = 'api/GET_STUDENTS_SUCCESS';
const GET_STUDENTS_FAILURE = 'api/GET_STUDENTS_FAILURE';

const DELETE_LESSON_REQUEST = 'api/DELETE_LESSON_REQUEST';
const DELETE_LESSON_SUCCESS = 'api/DELETE_LESSON_SUCCESS';
const DELETE_LESSON_FAILURE = 'api/DELETE_LESSON_FAILURE';

const DELETE_VACANCY_REQUEST = 'api/DELETE_VACANCY_REQUEST';
const DELETE_VACANCY_SUCCESS = 'api/DELETE_VACANCY_SUCCESS';
const DELETE_VACANCY_FAILURE = 'api/DELETE_VACANCY_FAILURE';

const DELETE_PROFILE_REQUEST = 'api/DELETE_PROFILE_REQUEST';
const DELETE_PROFILE_SUCCESS = 'api/DELETE_PROFILE_SUCCESS';
const DELETE_PROFILE_FAILURE = 'api/DELETE_PROFILE_FAILURE';

const ACCEPT_APPLICATION_REQUEST = 'api/ACCEPT_APPLICATION_REQUEST';
const ACCEPT_APPLICATION_SUCCESS = 'api/ACCEPT_APPLICATION_SUCCESS';
const ACCEPT_APPLICATION_FAILURE = 'api/ACCEPT_APPLICATION_FAILURE';

const ADD_APPLICATION_REQUEST = 'api/ADD_APPLICATION_REQUEST';
const ADD_APPLICATION_SUCCESS = 'api/ADD_APPLICATION_SUCCESS';
const ADD_APPLICATION_FAILURE = 'api/ADD_APPLICATION_FAILURE';

const ADD_LESSON_REQUEST = 'api/ADD_LESSON_REQUEST';
const ADD_LESSON_SUCCESS = 'api/ADD_LESSON_SUCCESS';
const ADD_LESSON_FAILURE = 'api/ADD_LESSON_FAILURE';

const DELETE_APPLICATION_REQUEST = 'api/DELETE_APPLICATION_REQUEST';
const DELETE_APPLICATION_SUCCESS = 'api/DELETE_APPLICATION_SUCCESS';
const DELETE_APPLICATION_FAILURE = 'api/DELETE_APPLICATION_FAILURE';

const GET_APPLICATIONS_REQUEST = 'api/GET_APPLICATIONS_REQUEST';
const GET_APPLICATIONS_SUCCESS = 'api/GET_APPLICATIONS_SUCCESS';
const GET_APPLICATIONS_FAILURE = 'api/GET_APPLICATIONS_FAILURE';

const GET_LESSONS_REQUEST = 'api/GET_LESSONS_REQUEST';
const GET_LESSONS_SUCCESS = 'api/GET_LESSONS_SUCCESS';
const GET_LESSONS_FAILURE = 'api/GET_LESSONS_FAILURE';

export const apiConstants = {
  CREATE_PROFILE_REQUEST, CREATE_PROFILE_SUCCESS, CREATE_PROFILE_FAILURE,
  
  CREATE_VACANCY_REQUEST, CREATE_VACANCY_SUCCESS, CREATE_VACANCY_FAILURE,
  
  ADD_LESSON_REQUEST, ADD_LESSON_SUCCESS, ADD_LESSON_FAILURE,
  
  GET_PROFILE_REQUEST, GET_PROFILE_SUCCESS, GET_PROFILE_FAILURE,
  
  UPDATE_PROFILE_REQUEST, UPDATE_PROFILE_SUCCESS, UPDATE_PROFILE_FAILURE,
  
  SEARCH_VACANCIES_REQUEST, SEARCH_VACANCIES_SUCCESS, SEARCH_VACANCIES_FAILURE,
  
  GET_STUDENTS_REQUEST, GET_STUDENTS_SUCCESS, GET_STUDENTS_FAILURE, 
  
  DELETE_LESSON_REQUEST, DELETE_LESSON_SUCCESS, DELETE_LESSON_FAILURE,
  
  DELETE_VACANCY_REQUEST, DELETE_VACANCY_SUCCESS, DELETE_VACANCY_FAILURE,
  
  DELETE_PROFILE_REQUEST, DELETE_PROFILE_SUCCESS, DELETE_PROFILE_FAILURE,
  
  ACCEPT_APPLICATION_REQUEST, ACCEPT_APPLICATION_SUCCESS, ACCEPT_APPLICATION_FAILURE,
  
  ADD_APPLICATION_REQUEST, ADD_APPLICATION_SUCCESS, ADD_APPLICATION_FAILURE,
  
  ADD_LESSON_REQUEST, ADD_LESSON_SUCCESS, ADD_LESSON_FAILURE,
  
  DELETE_APPLICATION_REQUEST, DELETE_APPLICATION_SUCCESS, DELETE_APPLICATION_FAILURE,

  GET_APPLICATIONS_REQUEST, GET_APPLICATIONS_SUCCESS, GET_APPLICATIONS_FAILURE,

  GET_LESSONS_REQUEST, GET_LESSONS_SUCCESS, GET_LESSONS_FAILURE,
};