const CREATE_APPLICATION_REQUEST = 'api/CREATE_APPLICATION_REQUEST';
const CREATE_APPLICATION_SUCCESS = 'api/CREATE_APPLICATION_SUCCESS';
const CREATE_APPLICATION_FAILURE = 'api/CREATE_APPLICATION_FAILURE';

const GET_TUTOR_APPLICATIONS_REQUEST = 'api/GET_TUTOR_APPLICATIONS_REQUEST';
const GET_TUTOR_APPLICATIONS_SUCCESS = 'api/GET_TUTOR_APPLICATIONS_SUCCESS';
const GET_TUTOR_APPLICATIONS_FAILURE = 'api/GET_TUTOR_APPLICATIONS_FAILURE';

const GET_STUDENT_APPLICATIONS_REQUEST = 'api/GET_STUDENT_APPLICATIONS_REQUEST';
const GET_STUDENT_APPLICATIONS_SUCCESS = 'api/GET_STUDENT_APPLICATIONS_SUCCESS';
const GET_STUDENT_APPLICATIONS_FAILURE = 'api/GET_STUDENT_APPLICATIONS_FAILURE';

const ACCEPT_APPLICATION_REQUEST = 'api/ACCEPT_APPLICATION_REQUEST';
const ACCEPT_APPLICATION_SUCCESS = 'api/ACCEPT_APPLICATION_SUCCESS';
const ACCEPT_APPLICATION_FAILURE = 'api/ACCEPT_APPLICATION_FAILURE';

const REJECT_APPLICATION_REQUEST = 'api/REJECT_APPLICATION_REQUEST';
const REJECT_APPLICATION_SUCCESS = 'api/REJECT_APPLICATION_SUCCESS';
const REJECT_APPLICATION_FAILURE = 'api/REJECT_APPLICATION_FAILURE';

export const apiApplicationConstants = {
    CREATE_APPLICATION_REQUEST, CREATE_APPLICATION_SUCCESS, CREATE_APPLICATION_FAILURE,
    GET_TUTOR_APPLICATIONS_REQUEST, GET_TUTOR_APPLICATIONS_SUCCESS, GET_TUTOR_APPLICATIONS_FAILURE,
    GET_STUDENT_APPLICATIONS_REQUEST, GET_STUDENT_APPLICATIONS_SUCCESS, GET_STUDENT_APPLICATIONS_FAILURE,
    ACCEPT_APPLICATION_REQUEST, ACCEPT_APPLICATION_SUCCESS, ACCEPT_APPLICATION_FAILURE,
    REJECT_APPLICATION_REQUEST, REJECT_APPLICATION_SUCCESS, REJECT_APPLICATION_FAILURE
};