const CREATE_LESSON_APPLICATION_REQUEST = 'api/CREATE_LESSON_APPLICATION_REQUEST';
const CREATE_LESSON_APPLICATION_SUCCESS = 'api/CREATE_LESSON_APPLICATION_SUCCESS';
const CREATE_LESSON_APPLICATION_FAILURE = 'api/CREATE_LESSON_APPLICATION_FAILURE';

const GET_INCOMING_LESSON_APPLICATIONS_REQUEST = 'api/GET_INCOMING_LESSON_APPLICATIONS_REQUEST';
const GET_INCOMING_LESSON_APPLICATIONS_SUCCESS = 'api/GET_INCOMING_LESSON_APPLICATIONS_SUCCESS';
const GET_INCOMING_LESSON_APPLICATIONS_FAILURE = 'api/GET_INCOMING_LESSON_APPLICATIONS_FAILURE';

const GET_OUTGOING_LESSON_APPLICATIONS_REQUEST = 'api/GET_OUTGOING_LESSON_APPLICATIONS_REQUEST';
const GET_OUTGOING_LESSON_APPLICATIONS_SUCCESS = 'api/GET_OUTGOING_LESSON_APPLICATIONS_SUCCESS';
const GET_OUTGOING_LESSON_APPLICATIONS_FAILURE = 'api/GET_OUTGOING_LESSON_APPLICATIONS_FAILURE';

const ACCEPT_LESSON_APPLICATION_REQUEST = 'api/ACCEPT_LESSON_APPLICATION_REQUEST';
const ACCEPT_LESSON_APPLICATION_SUCCESS = 'api/ACCEPT_LESSON_APPLICATION_SUCCESS';
const ACCEPT_LESSON_APPLICATION_FAILURE = 'api/ACCEPT_LESSON_APPLICATION_FAILURE';

const REJECT_LESSON_APPLICATION_REQUEST = 'api/REJECT_LESSON_APPLICATION_REQUEST';
const REJECT_LESSON_APPLICATION_SUCCESS = 'api/REJECT_LESSON_APPLICATION_SUCCESS';
const REJECT_LESSON_APPLICATION_FAILURE = 'api/REJECT_LESSON_APPLICATION_FAILURE';

export const apiLessonApplicationConstants = {
    CREATE_LESSON_APPLICATION_REQUEST, CREATE_LESSON_APPLICATION_SUCCESS, CREATE_LESSON_APPLICATION_FAILURE,
    GET_INCOMING_LESSON_APPLICATIONS_REQUEST, GET_INCOMING_LESSON_APPLICATIONS_SUCCESS,
    GET_INCOMING_LESSON_APPLICATIONS_FAILURE, GET_OUTGOING_LESSON_APPLICATIONS_REQUEST,
    GET_OUTGOING_LESSON_APPLICATIONS_SUCCESS, GET_OUTGOING_LESSON_APPLICATIONS_FAILURE,
    ACCEPT_LESSON_APPLICATION_REQUEST, ACCEPT_LESSON_APPLICATION_SUCCESS, ACCEPT_LESSON_APPLICATION_FAILURE,
    REJECT_LESSON_APPLICATION_REQUEST, REJECT_LESSON_APPLICATION_SUCCESS, REJECT_LESSON_APPLICATION_FAILURE
};