const CREATE_PROFILE_REQUEST = 'api/CREATE_PROFILE_REQUEST';
const CREATE_PROFILE_SUCCESS = 'api/CREATE_PROFILE_SUCCESS';
const CREATE_PROFILE_FAILURE = 'api/CREATE_PROFILE_FAILURE';

const GET_PROFILE_REQUEST = 'api/GET_PROFILE_REQUEST';
const GET_PROFILE_SUCCESS = 'api/GET_PROFILE_SUCCESS';
const GET_PROFILE_FAILURE = 'api/GET_PROFILE_FAILURE';

const UPDATE_PROFILE_REQUEST = 'api/UPDATE_PROFILE_REQUEST';
const UPDATE_PROFILE_SUCCESS = 'api/UPDATE_PROFILE_SUCCESS';
const UPDATE_PROFILE_FAILURE = 'api/UPDATE_PROFILE_FAILURE';

const DEACTIVATE_PROFILE_REQUEST = 'api/DEACTIVATE_PROFILE_REQUEST';
const DEACTIVATE_PROFILE_SUCCESS = 'api/DEACTIVATE_PROFILE_SUCCESS';
const DEACTIVATE_PROFILE_FAILURE = 'api/DEACTIVATE_PROFILE_FAILURE';

export const apiProfileConstants = {
    CREATE_PROFILE_REQUEST, CREATE_PROFILE_SUCCESS, CREATE_PROFILE_FAILURE,
    GET_PROFILE_REQUEST, GET_PROFILE_SUCCESS, GET_PROFILE_FAILURE,
    UPDATE_PROFILE_REQUEST, UPDATE_PROFILE_SUCCESS, UPDATE_PROFILE_FAILURE,
    DEACTIVATE_PROFILE_REQUEST, DEACTIVATE_PROFILE_SUCCESS, DEACTIVATE_PROFILE_FAILURE
};