const VACANCIES_FILTER_UPDATE = 'vacancies/VACANCIES_FILTER_UPDATE';
const VACANCIES_FILTER_DELETE = 'vacancies/VACANCIES_FILTER_DELETE';

export const filterConstants = {
  VACANCIES_FILTER_UPDATE, VACANCIES_FILTER_DELETE,
};