export const notificationEventTypes = {
  STUDENT_APPLICATION_CREATION: 0,
  STUDENT_APPLICATION_ACCEPT: 1,
  STUDENT_APPLICATION_REJECT: 2,
  LESSON_CREATION: 3,
  DELETION_FROM_STUDENTS: 4,
  LESSON_CHANGING: 5,
  LESSON_DEACTIVATION: 6,
  LESSON_APPLICATION_CREATION: 7,
  LESSON_APPLICATION_ACCEPT: 8,
  LESSON_APPLICATION_REJECT: 9,
  PAYMENT_APPLICATION_CREATION: 10,
  PAYMENT_APPLICATION_ACCEPT: 11,
  PAYMENT_APPLICATION_REJECT: 12,
};

export const notificationLabels = {
  [notificationEventTypes.STUDENT_APPLICATION_CREATION]: "Заявка на поступление в список учеников",
  [notificationEventTypes.STUDENT_APPLICATION_ACCEPT]: "Принятие заявки на поступление к учителю",
  [notificationEventTypes.STUDENT_APPLICATION_REJECT]: "Отклонение заявки на поступление к учителю",
  [notificationEventTypes.LESSON_CREATION]: "Создание урока",
  [notificationEventTypes.DELETION_FROM_STUDENTS]: "Удаление из списка учеников",
  [notificationEventTypes.LESSON_CHANGING]: "Изменение урока",
  [notificationEventTypes.LESSON_DEACTIVATION]: "Отмена урока",
  [notificationEventTypes.LESSON_APPLICATION_CREATION]: "Заявка на изменение урока",
  [notificationEventTypes.LESSON_APPLICATION_ACCEPT]: "Принятие заявки на изменение урока",
  [notificationEventTypes.LESSON_APPLICATION_REJECT]: "Отклонение заявки на изменение урока",
  [notificationEventTypes.PAYMENT_APPLICATION_CREATION]: "Заявка на оплату занятия",
  [notificationEventTypes.PAYMENT_APPLICATION_ACCEPT]: "Принятие заявки на оплату занятия",
  [notificationEventTypes.PAYMENT_APPLICATION_REJECT]: "Отклонение заявки на оплату занятия",
};
