const VK_GET_USER_INFO_FETCHED = 'vk/getUserInfoResult';
const VK_GET_USER_INFO_FAILED = 'vk/getUserInfoFailed';

const VK_GET_ACCESS_TOKEN_FETCHED = 'vk/accessTokenFetched';
const VK_GET_ACCESS_TOKEN_FAILED = 'vk/accessTokenFailed';

const VK_NOTIFICATION_STATUS_FETCHED = 'vk/notificationsStatusFetched';
const VK_NOTIFICATION_STATUS_FAILED = 'vk/notificationsStatusFailed';

const VK_API_USERS_GET_FETCHED = 'vk/VK_API_USERS_GET_FETCHED';
const VK_API_USERS_GET_FAILED = 'vk/VK_API_USERS_GET_FAILED';

export const vkConstants = {
  VK_GET_USER_INFO_FETCHED, VK_GET_USER_INFO_FAILED,
  VK_GET_ACCESS_TOKEN_FETCHED, VK_GET_ACCESS_TOKEN_FAILED,
  VK_NOTIFICATION_STATUS_FETCHED, VK_NOTIFICATION_STATUS_FAILED,
  VK_API_USERS_GET_FETCHED, VK_API_USERS_GET_FAILED,
};
