const VK_INIT_REQUEST = 'vk/VK_INIT_REQUEST';
const VK_INIT_SUCCESS = 'vk/VK_INIT_SUCCESS';
const VK_INIT_FAILURE = 'vk/VK_INIT_FAILURE';

const VK_GET_USER_INFO_REQUEST = 'vk/VK_GET_USER_INFO_REQUEST';
const VK_GET_USER_INFO_SUCCESS = 'vk/VK_GET_USER_INFO_SUCCESS';
const VK_GET_USER_INFO_FAILURE = 'vk/VK_GET_USER_INFO_FAILURE';

const VK_GET_ACCESS_TOKEN_FETCHED = 'vk/accessTokenFetched';
const VK_GET_ACCESS_TOKEN_FAILED = 'vk/accessTokenFailed';
const VK_NOTIFICATION_STATUS_FETCHED = 'vk/notificationsStatusFetched';
const VK_NOTIFICATION_STATUS_FAILED = 'vk/notificationsStatusFailed';
const VK_INSETS_FETCHED = 'vk/insetsFetched';

export const vkConstants = {
  VK_INIT_REQUEST, VK_INIT_SUCCESS, VK_INIT_FAILURE,
  VK_GET_USER_INFO_REQUEST, VK_GET_USER_INFO_SUCCESS, VK_GET_USER_INFO_FAILURE,
  
  VK_GET_ACCESS_TOKEN_FETCHED, VK_GET_ACCESS_TOKEN_FAILED,
  VK_NOTIFICATION_STATUS_FETCHED, VK_NOTIFICATION_STATUS_FAILED,
  VK_INSETS_FETCHED
};
