const VK_INIT = 'vk/VK_INIT';
const VK_ALLOW_NOTIFICATIONS = 'vk/VK_ALLOW_NOTIFICATIONS';
const VK_DENY_NOTIFICATIONS = 'vk/VK_DENY_NOTIFICATIONS';

const VK_GET_USER_INFO_REQUEST = 'vk/VK_GET_USER_INFO_REQUEST';
const VK_GET_USER_INFO_FETCHED = 'vk/VK_GET_USER_INFO_FETCHED';
const VK_GET_USER_INFO_FAILED = 'vk/VK_GET_USER_INFO_FAILED';

const VK_GET_ACCESS_TOKEN_REQUEST = 'vk/VK_GET_ACCESS_TOKEN_REQUEST';
const VK_GET_ACCESS_TOKEN_FETCHED = 'vk/VK_GET_ACCESS_TOKEN_FETCHED';
const VK_GET_ACCESS_TOKEN_FAILED = 'vk/VK_GET_ACCESS_TOKEN_FAILED';

export const vkAppsConstants = {
  VK_INIT, VK_ALLOW_NOTIFICATIONS, VK_DENY_NOTIFICATIONS,
  VK_GET_USER_INFO_REQUEST, VK_GET_USER_INFO_FETCHED, VK_GET_USER_INFO_FAILED,
  VK_GET_ACCESS_TOKEN_REQUEST, VK_GET_ACCESS_TOKEN_FETCHED, VK_GET_ACCESS_TOKEN_FAILED,
};
