const VK_API_USERS_GET_REQUEST = 'vk/VK_API_USERS_GET_REQUEST';
const VK_API_USERS_GET_FETCHED = 'vk/VK_API_USERS_GET_FETCHED';
const VK_API_USERS_GET_FAILED = 'vk/VK_API_USERS_GET_FAILED';

const VK_API_NOTIFICATION_STATUS_REQUEST = 'vk/VK_API_NOTIFICATION_STATUS_REQUEST';
const VK_API_NOTIFICATION_STATUS_FETCHED = 'vk/VK_API_NOTIFICATION_STATUS_FETCHED';
const VK_API_NOTIFICATION_STATUS_FAILED = 'vk/VK_API_NOTIFICATION_STATUS_FAILED';

export const vkApiConstants = {
  VK_API_USERS_GET_REQUEST, VK_API_USERS_GET_FETCHED, VK_API_USERS_GET_FAILED,
  VK_API_NOTIFICATION_STATUS_REQUEST, VK_API_NOTIFICATION_STATUS_FETCHED, VK_API_NOTIFICATION_STATUS_FAILED,
};
