# Generated by Django 2.2a1 on 2019-01-28 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subject', models.CharField(max_length=128)),
                ('ege', models.BooleanField(default=False)),
                ('oge', models.BooleanField(default=False)),
                ('foreign_lang_cert', models.BooleanField(default=False)),
                ('primary_school', models.BooleanField(default=False)),
                ('secondary_school', models.BooleanField(default=False)),
                ('olympiads', models.BooleanField(default=False)),
                ('university', models.BooleanField(default=False)),
                ('home_schooling', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('extra_info', models.TextField(blank=True, max_length=256)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
