# Generated by Django 2.1.7 on 2019-02-20 00:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_auto_20190209_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=10000)]),
        ),
    ]
