# Generated by Django 2.1.7 on 2019-02-22 23:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_auto_20190220_0010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ('-id',), 'verbose_name': 'vacancy', 'verbose_name_plural': 'vacancies'},
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='ege',
            field=models.BooleanField(default=False, verbose_name='ege'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='extra_info',
            field=models.TextField(blank=True, max_length=256, verbose_name='extra info'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='foreign_lang_cert',
            field=models.BooleanField(default=False, verbose_name='foreign language certificate'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='home_schooling',
            field=models.BooleanField(default=False, verbose_name='home schooling'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='oge',
            field=models.BooleanField(default=False, verbose_name='oge'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='olympiads',
            field=models.BooleanField(default=False, verbose_name='olympiads'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_owner', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=10000)], verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='primary_school',
            field=models.BooleanField(default=False, verbose_name='primary school'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='secondary_school',
            field=models.BooleanField(default=False, verbose_name='secondary school'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='subject',
            field=models.CharField(max_length=128, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='university',
            field=models.BooleanField(default=False, verbose_name='university'),
        ),
    ]
