# Generated by Django 2.1.7 on 2019-03-10 15:06

from django.conf import settings
from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0004_auto_20190222_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='extra_info',
            field=models.TextField(blank=True, max_length=128, validators=[utils.validators.NoSpecialSymbolsValidator()], verbose_name='extra info'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='subject',
            field=models.CharField(max_length=128, validators=[utils.validators.NoSpecialSymbolsValidator()], verbose_name='subject'),
        ),
        migrations.AlterUniqueTogether(
            name='vacancy',
            unique_together={('owner', 'subject')},
        ),
    ]
