# Generated by Django 2.1.7 on 2019-04-09 13:09

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_auto_20190310_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='extra_info',
            field=models.TextField(blank=True, max_length=128, validators=[utils.validators.NoSpecialSymbolsValidator(), utils.validators.validate_profanity], verbose_name='extra info'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='subject',
            field=models.CharField(max_length=128, validators=[utils.validators.NoSpecialSymbolsValidator(), utils.validators.validate_profanity], verbose_name='subject'),
        ),
    ]
