const CREATE_LESSON_REQUEST = 'api/CREATE_LESSON_REQUEST';
const CREATE_LESSON_SUCCESS = 'api/CREATE_LESSON_SUCCESS';
const CREATE_LESSON_FAILURE = 'api/CREATE_LESSON_FAILURE';

const GET_LESSONS_REQUEST = 'api/GET_LESSONS_REQUEST';
const GET_LESSONS_SUCCESS = 'api/GET_LESSONS_SUCCESS';
const GET_LESSONS_FAILURE = 'api/GET_LESSONS_FAILURE';

const UPDATE_LESSONS_REQUEST = 'api/UPDATE_LESSONS_REQUEST';
const UPDATE_LESSONS_SUCCESS = 'api/UPDATE_LESSONS_SUCCESS';
const UPDATE_LESSONS_FAILURE = 'api/UPDATE_LESSONS_FAILURE';

const DELETE_LESSON_REQUEST = 'api/DELETE_LESSON_REQUEST';
const DELETE_LESSON_SUCCESS = 'api/DELETE_LESSON_SUCCESS';
const DELETE_LESSON_FAILURE = 'api/DELETE_LESSON_FAILURE';

export const lessonsConstants = {
  CREATE_LESSON_REQUEST, CREATE_LESSON_SUCCESS, CREATE_LESSON_FAILURE,
  GET_LESSONS_REQUEST, GET_LESSONS_SUCCESS, GET_LESSONS_FAILURE,
  UPDATE_LESSONS_REQUEST, UPDATE_LESSONS_SUCCESS, UPDATE_LESSONS_FAILURE,
  DELETE_LESSON_REQUEST, DELETE_LESSON_SUCCESS, DELETE_LESSON_FAILURE,
};