const CREATE_LESSON_REQUEST = 'API/CREATE_LESSON_REQUEST';
const CREATE_LESSON_SUCCESS = 'API/CREATE_LESSON_SUCCESS';
const CREATE_LESSON_FAILURE = 'API/CREATE_LESSON_FAILURE';

const GET_LESSONS_LIST_REQUEST = 'API/GET_LESSONS_LIST_REQUEST';
const GET_LESSONS_LIST_SUCCESS = 'API/GET_LESSONS_LIST_SUCCESS';
const GET_LESSONS_LIST_FAILURE = 'API/GET_LESSONS_LIST_FAILURE';

const GET_LESSON_REQUEST = 'API/GET_LESSON_REQUEST';
const GET_LESSON_SUCCESS = 'API/GET_LESSON_SUCCESS';
const GET_LESSON_FAILURE = 'API/GET_LESSON_FAILURE';

const UPDATE_LESSON_REQUEST = 'API/UPDATE_LESSON_REQUEST';
const UPDATE_LESSON_SUCCESS = 'API/UPDATE_LESSON_SUCCESS';
const UPDATE_LESSON_FAILURE = 'API/UPDATE_LESSON_FAILURE';

const DELETE_LESSON_REQUEST = 'API/DELETE_LESSON_REQUEST';
const DELETE_LESSON_SUCCESS = 'API/DELETE_LESSON_SUCCESS';
const DELETE_LESSON_FAILURE = 'API/DELETE_LESSON_FAILURE';

export const lessonsConstants = {
  CREATE_LESSON_REQUEST,
  CREATE_LESSON_SUCCESS,
  CREATE_LESSON_FAILURE,

  GET_LESSONS_LIST_REQUEST,
  GET_LESSONS_LIST_SUCCESS,
  GET_LESSONS_LIST_FAILURE,

  GET_LESSON_REQUEST,
  GET_LESSON_SUCCESS,
  GET_LESSON_FAILURE,

  UPDATE_LESSON_REQUEST,
  UPDATE_LESSON_SUCCESS,
  UPDATE_LESSON_FAILURE,

  DELETE_LESSON_REQUEST,
  DELETE_LESSON_SUCCESS,
  DELETE_LESSON_FAILURE,
};