const GET_NOTIFICATIONS_LIST_REQUEST = 'API/GET_NOTIFICATIONS_LIST_REQUEST';
const GET_NOTIFICATIONS_LIST_SUCCESS = 'API/GET_NOTIFICATIONS_LIST_SUCCESS';
const GET_NOTIFICATIONS_LIST_FAILURE = 'API/GET_NOTIFICATIONS_LIST_FAILURE';

const GET_UNREAD_NOTIFICATIONS_LIST_REQUEST = 'API/GET_UNREAD_NOTIFICATIONS_LIST_REQUEST';
const GET_UNREAD_NOTIFICATIONS_LIST_SUCCESS = 'API/GET_UNREAD_NOTIFICATIONS_LIST_SUCCESS';
const GET_UNREAD_NOTIFICATIONS_LIST_FAILURE = 'API/GET_UNREAD_NOTIFICATIONS_LIST_FAILURE';

const GET_READ_NOTIFICATIONS_LIST_REQUEST = 'API/GET_READ_NOTIFICATIONS_LIST_REQUEST';
const GET_READ_NOTIFICATIONS_LIST_SUCCESS = 'API/GET_READ_NOTIFICATIONS_LIST_SUCCESS';
const GET_READ_NOTIFICATIONS_LIST_FAILURE = 'API/GET_READ_NOTIFICATIONS_LIST_FAILURE';

const GET_NOTIFICATION_REQUEST = 'API/GET_NOTIFICATION_REQUEST';
const GET_NOTIFICATION_SUCCESS = 'API/GET_NOTIFICATION_SUCCESS';
const GET_NOTIFICATION_FAILURE = 'API/GET_NOTIFICATION_FAILURE';

const SET_UNREAD_NOTIFICATION_REQUEST = 'API/SET_UNREAD_NOTIFICATION_REQUEST';
const SET_UNREAD_NOTIFICATION_SUCCESS = 'API/SET_UNREAD_NOTIFICATION_SUCCESS';
const SET_UNREAD_NOTIFICATION_FAILURE = 'API/SET_UNREAD_NOTIFICATION_FAILURE';

export const notificationsConstants = {
  GET_NOTIFICATIONS_LIST_REQUEST,
  GET_NOTIFICATIONS_LIST_SUCCESS,
  GET_NOTIFICATIONS_LIST_FAILURE,

  GET_UNREAD_NOTIFICATIONS_LIST_REQUEST,
  GET_UNREAD_NOTIFICATIONS_LIST_SUCCESS,
  GET_UNREAD_NOTIFICATIONS_LIST_FAILURE,

  GET_READ_NOTIFICATIONS_LIST_REQUEST,
  GET_READ_NOTIFICATIONS_LIST_SUCCESS,
  GET_READ_NOTIFICATIONS_LIST_FAILURE,

  GET_NOTIFICATION_REQUEST,
  GET_NOTIFICATION_SUCCESS,
  GET_NOTIFICATION_FAILURE,

  SET_UNREAD_NOTIFICATION_REQUEST,
  SET_UNREAD_NOTIFICATION_SUCCESS,
  SET_UNREAD_NOTIFICATION_FAILURE,
};