const GET_NOTIFICATIONS_REQUEST = 'api/GET_NOTIFICATIONS_REQUEST';
const GET_NOTIFICATIONS_SUCCESS = 'api/GET_NOTIFICATIONS_SUCCESS';
const GET_NOTIFICATIONS_FAILURE = 'api/GET_NOTIFICATIONS_FAILURE';

const MARK_NOTIFICATION_AS_SEEN_REQUEST = 'api/MARK_NOTIFICATION_AS_SEEN_REQUEST';
const MARK_NOTIFICATION_AS_SEEN_SUCCESS = 'api/MARK_NOTIFICATION_AS_SEEN_SUCCESS';
const MARK_NOTIFICATION_AS_SEEN_FAILURE = 'api/MARK_NOTIFICATION_AS_SEEN_FAILURE';

export const notificationsConstants = {
  GET_NOTIFICATIONS_REQUEST, GET_NOTIFICATIONS_SUCCESS, GET_NOTIFICATIONS_FAILURE,
  MARK_NOTIFICATION_AS_SEEN_REQUEST, MARK_NOTIFICATION_AS_SEEN_SUCCESS, MARK_NOTIFICATION_AS_SEEN_FAILURE,
};
