const GET_STUDENT_REQUESTS_LIST_REQUEST = 'api/GET_STUDENT_REQUESTS_LIST_REQUEST';
const GET_STUDENT_REQUESTS_LIST_SUCCESS = 'api/GET_STUDENT_REQUESTS_LIST_SUCCESS';
const GET_STUDENT_REQUESTS_LIST_FAILURE = 'api/GET_STUDENT_REQUESTS_LIST_FAILURE';

const CREATE_STUDENT_REQUEST_REQUEST = 'api/CREATE_STUDENT_REQUEST_REQUEST';
const CREATE_STUDENT_REQUEST_SUCCESS = 'api/CREATE_STUDENT_REQUEST_SUCCESS';
const CREATE_STUDENT_REQUEST_FAILURE = 'api/CREATE_STUDENT_REQUEST_FAILURE';

const GET_STUDENT_REQUEST_REQUEST = 'api/GET_STUDENT_REQUEST_REQUEST';
const GET_STUDENT_REQUEST_SUCCESS = 'api/GET_STUDENT_REQUEST_SUCCESS';
const GET_STUDENT_REQUEST_FAILURE = 'api/GET_STUDENT_REQUEST_FAILURE';

const DELETE_STUDENT_REQUEST_REQUEST = 'api/DELETE_STUDENT_REQUEST_REQUEST';
const DELETE_STUDENT_REQUEST_SUCCESS = 'api/DELETE_STUDENT_REQUEST_SUCCESS';
const DELETE_STUDENT_REQUEST_FAILURE = 'api/DELETE_STUDENT_REQUEST_FAILURE';

const ACCEPT_STUDENT_REQUEST_REQUEST = 'api/ACCEPT_STUDENT_REQUEST_REQUEST';
const ACCEPT_STUDENT_REQUEST_SUCCESS = 'api/ACCEPT_STUDENT_REQUEST_SUCCESS';
const ACCEPT_STUDENT_REQUEST_FAILURE = 'api/ACCEPT_STUDENT_REQUEST_FAILURE';

const GET_STUDENTS_LIST_REQUEST = 'api/GET_STUDENTS_LIST_REQUEST';
const GET_STUDENTS_LIST_SUCCESS = 'api/GET_STUDENTS_LIST_SUCCESS';
const GET_STUDENTS_LIST_FAILURE = 'api/GET_STUDENTS_LIST_FAILURE';

const GET_STUDENT_REQUEST = 'api/GET_STUDENT_REQUEST';
const GET_STUDENT_SUCCESS = 'api/GET_STUDENT_SUCCESS';
const GET_STUDENT_FAILURE = 'api/GET_STUDENT_FAILURE';

const DELETE_STUDENT_REQUEST = 'api/DELETE_STUDENT_REQUEST';
const DELETE_STUDENT_SUCCESS = 'api/DELETE_STUDENT_SUCCESS';
const DELETE_STUDENT_FAILURE = 'api/DELETE_STUDENT_FAILURE';

export const tutorsConstants = {
  GET_STUDENT_REQUESTS_LIST_REQUEST,
  GET_STUDENT_REQUESTS_LIST_SUCCESS,
  GET_STUDENT_REQUESTS_LIST_FAILURE,

  CREATE_STUDENT_REQUEST_REQUEST,
  CREATE_STUDENT_REQUEST_SUCCESS,
  CREATE_STUDENT_REQUEST_FAILURE,

  GET_STUDENT_REQUEST_REQUEST,
  GET_STUDENT_REQUEST_SUCCESS,
  GET_STUDENT_REQUEST_FAILURE,

  DELETE_STUDENT_REQUEST_REQUEST,
  DELETE_STUDENT_REQUEST_SUCCESS,
  DELETE_STUDENT_REQUEST_FAILURE,

  ACCEPT_STUDENT_REQUEST_REQUEST,
  ACCEPT_STUDENT_REQUEST_SUCCESS,
  ACCEPT_STUDENT_REQUEST_FAILURE,

  GET_STUDENTS_LIST_REQUEST,
  GET_STUDENTS_LIST_SUCCESS,
  GET_STUDENTS_LIST_FAILURE,

  GET_STUDENT_REQUEST,
  GET_STUDENT_SUCCESS,
  GET_STUDENT_FAILURE,

  DELETE_STUDENT_REQUEST,
  DELETE_STUDENT_SUCCESS,
  DELETE_STUDENT_FAILURE,
};
