const GET_USERS_LIST_REQUEST = 'API/GET_USERS_LIST_REQUEST';
const GET_USERS_LIST_SUCCESS = 'API/GET_USERS_LIST_SUCCESS';
const GET_USERS_LIST_FAILURE = 'API/GET_USERS_LIST_FAILURE';

const CREATE_USER_REQUEST = 'API/CREATE_USER_REQUEST';
const CREATE_USER_SUCCESS = 'API/CREATE_USER_SUCCESS';
const CREATE_USER_FAILURE = 'API/CREATE_USER_FAILURE';

const GET_USER_REQUEST = 'API/GET_USER_REQUEST';
const GET_USER_SUCCESS = 'API/GET_USER_SUCCESS';
const GET_USER_FAILURE = 'API/GET_USER_FAILURE';

const UPDATE_USER_REQUEST = 'API/UPDATE_USER_REQUEST';
const UPDATE_USER_SUCCESS = 'API/UPDATE_USER_SUCCESS';
const UPDATE_USER_FAILURE = 'API/UPDATE_USER_FAILURE';

const UPLOAD_AVATAR_REQUEST = 'API/UPLOAD_AVATAR_REQUEST';
const UPLOAD_AVATAR_SUCCESS = 'API/UPLOAD_AVATAR_SUCCESS';
const UPLOAD_AVATAR_FAILURE = 'API/UPLOAD_AVATAR_FAILURE';

export const usersConstants = {
  GET_USERS_LIST_REQUEST,
  GET_USERS_LIST_SUCCESS,
  GET_USERS_LIST_FAILURE,

  CREATE_USER_REQUEST,
  CREATE_USER_SUCCESS,
  CREATE_USER_FAILURE,

  GET_USER_REQUEST,
  GET_USER_SUCCESS,
  GET_USER_FAILURE,

  UPDATE_USER_REQUEST,
  UPDATE_USER_SUCCESS,
  UPDATE_USER_FAILURE,

  UPLOAD_AVATAR_REQUEST,
  UPLOAD_AVATAR_SUCCESS,
  UPLOAD_AVATAR_FAILURE,
};
