const GET_USERS_LIST_REQUEST = 'api/GET_USERS_LIST_REQUEST';
const GET_USERS_LIST_SUCCESS = 'api/GET_USERS_LIST_SUCCESS';
const GET_USERS_LIST_FAILURE = 'api/GET_USERS_LIST_FAILURE';

const CREATE_USER_REQUEST = 'api/CREATE_USER_REQUEST';
const CREATE_USER_SUCCESS = 'api/CREATE_USER_SUCCESS';
const CREATE_USER_FAILURE = 'api/CREATE_USER_FAILURE';

const GET_USER_REQUEST = 'api/GET_USER_REQUEST';
const GET_USER_SUCCESS = 'api/GET_USER_SUCCESS';
const GET_USER_FAILURE = 'api/GET_USER_FAILURE';

const UPDATE_USER_REQUEST = 'api/UPDATE_USER_REQUEST';
const UPDATE_USER_SUCCESS = 'api/UPDATE_USER_SUCCESS';
const UPDATE_USER_FAILURE = 'api/UPDATE_USER_FAILURE';

const DELETE_USER_REQUEST = 'api/DELETE_USER_REQUEST';
const DELETE_USER_SUCCESS = 'api/DELETE_USER_SUCCESS';
const DELETE_USER_FAILURE = 'api/DELETE_USER_FAILURE';

export const usersConstants = {
  GET_USERS_LIST_REQUEST,
  GET_USERS_LIST_SUCCESS,
  GET_USERS_LIST_FAILURE,

  CREATE_USER_REQUEST,
  CREATE_USER_SUCCESS,
  CREATE_USER_FAILURE,

  GET_USER_REQUEST,
  GET_USER_SUCCESS,
  GET_USER_FAILURE,

  UPDATE_USER_REQUEST,
  UPDATE_USER_SUCCESS,
  UPDATE_USER_FAILURE,
  
  DELETE_USER_REQUEST,
  DELETE_USER_SUCCESS,
  DELETE_USER_FAILURE,
};
