const CREATE_VACANCY_REQUEST = 'API/CREATE_VACANCY_REQUEST';
const CREATE_VACANCY_SUCCESS = 'API/CREATE_VACANCY_SUCCESS';
const CREATE_VACANCY_FAILURE = 'API/CREATE_VACANCY_FAILURE';

const UPDATE_VACANCY_REQUEST = 'API/UPDATE_VACANCY_REQUEST';
const UPDATE_VACANCY_SUCCESS = 'API/UPDATE_VACANCY_SUCCESS';
const UPDATE_VACANCY_FAILURE = 'API/UPDATE_VACANCY_FAILURE';

const SEARCH_VACANCIES_REQUEST = 'API/SEARCH_VACANCIES_REQUEST';
const SEARCH_VACANCIES_SUCCESS = 'API/SEARCH_VACANCIES_SUCCESS';
const SEARCH_VACANCIES_FAILURE = 'API/SEARCH_VACANCIES_FAILURE';

const GET_VACANCY_REQUEST = 'API/GET_VACANCY_REQUEST';
const GET_VACANCY_SUCCESS = 'API/GET_VACANCY_SUCCESS';
const GET_VACANCY_FAILURE = 'API/GET_VACANCY_FAILURE';

const DELETE_VACANCY_REQUEST = 'API/DELETE_VACANCY_REQUEST';
const DELETE_VACANCY_SUCCESS = 'API/DELETE_VACANCY_SUCCESS';
const DELETE_VACANCY_FAILURE = 'API/DELETE_VACANCY_FAILURE';

export const vacanciesConstants = {
  CREATE_VACANCY_REQUEST,
  CREATE_VACANCY_SUCCESS,
  CREATE_VACANCY_FAILURE,

  UPDATE_VACANCY_REQUEST,
  UPDATE_VACANCY_SUCCESS,
  UPDATE_VACANCY_FAILURE,

  SEARCH_VACANCIES_REQUEST,
  SEARCH_VACANCIES_SUCCESS,
  SEARCH_VACANCIES_FAILURE,

  GET_VACANCY_REQUEST,
  GET_VACANCY_SUCCESS,
  GET_VACANCY_FAILURE,

  DELETE_VACANCY_REQUEST,
  DELETE_VACANCY_SUCCESS,
  DELETE_VACANCY_FAILURE,
};
