const CREATE_VK_APPS_USER_REQUEST = 'API/CREATE_VK_APPS_USER_REQUEST';
const CREATE_VK_APPS_USER_SUCCESS = 'API/CREATE_VK_APPS_USER_SUCCESS';
const CREATE_VK_APPS_USER_FAILURE = 'API/CREATE_VK_APPS_USER_FAILURE';

const GET_VK_APPS_USER_REQUEST = 'API/GET_VK_APPS_USER_REQUEST';
const GET_VK_APPS_USER_SUCCESS = 'API/GET_VK_APPS_USER_SUCCESS';
const GET_VK_APPS_USER_FAILURE = 'API/GET_VK_APPS_USER_FAILURE';

const DELETE_VK_APPS_USER_REQUEST = 'API/DELETE_VK_APPS_USER_REQUEST';
const DELETE_VK_APPS_USER_SUCCESS = 'API/DELETE_VK_APPS_USER_SUCCESS';
const DELETE_VK_APPS_USER_FAILURE = 'API/DELETE_VK_APPS_USER_FAILURE';

const CONNECT_VK_APPS_USER_REQUEST = 'API/CONNECT_VK_APPS_USER_REQUEST';
const CONNECT_VK_APPS_USER_SUCCESS = 'API/CONNECT_VK_APPS_USER_SUCCESS';
const CONNECT_VK_APPS_USER_FAILURE = 'API/CONNECT_VK_APPS_USER_FAILURE';

const RETRIEVE_VK_APPS_USER_BY_USER_ID_REQUEST = 'API/RETRIEVE_VK_APPS_USER_BY_USER_ID_REQUEST';
const RETRIEVE_VK_APPS_USER_BY_USER_ID_SUCCESS = 'API/RETRIEVE_VK_APPS_USER_BY_USER_ID_SUCCESS';
const RETRIEVE_VK_APPS_USER_BY_USER_ID_FAILURE = 'API/RETRIEVE_VK_APPS_USER_BY_USER_ID_FAILURE';

export const vkAppsUsersConstants = {
  CREATE_VK_APPS_USER_REQUEST,
  CREATE_VK_APPS_USER_SUCCESS,
  CREATE_VK_APPS_USER_FAILURE,

  GET_VK_APPS_USER_REQUEST,
  GET_VK_APPS_USER_SUCCESS,
  GET_VK_APPS_USER_FAILURE,

  DELETE_VK_APPS_USER_REQUEST,
  DELETE_VK_APPS_USER_SUCCESS,
  DELETE_VK_APPS_USER_FAILURE,

  CONNECT_VK_APPS_USER_REQUEST,
  CONNECT_VK_APPS_USER_SUCCESS,
  CONNECT_VK_APPS_USER_FAILURE,

  RETRIEVE_VK_APPS_USER_BY_USER_ID_REQUEST,
  RETRIEVE_VK_APPS_USER_BY_USER_ID_SUCCESS,
  RETRIEVE_VK_APPS_USER_BY_USER_ID_FAILURE,
};