const CREATE_VK_APPS_USER_REQUEST = 'api/CREATE_VK_APPS_USER_REQUEST';
const CREATE_VK_APPS_USER_SUCCESS = 'api/CREATE_VK_APPS_USER_SUCCESS';
const CREATE_VK_APPS_USER_FAILURE = 'api/CREATE_VK_APPS_USER_FAILURE';

const GET_VK_APPS_USER_REQUEST = 'api/GET_VK_APPS_USER_REQUEST';
const GET_VK_APPS_USER_SUCCESS = 'api/GET_VK_APPS_USER_SUCCESS';
const GET_VK_APPS_USER_FAILURE = 'api/GET_VK_APPS_USER_FAILURE';

const DELETE_VK_APPS_USER_REQUEST = 'api/DELETE_VK_APPS_USER_REQUEST';
const DELETE_VK_APPS_USER_SUCCESS = 'api/DELETE_VK_APPS_USER_SUCCESS';
const DELETE_VK_APPS_USER_FAILURE = 'api/DELETE_VK_APPS_USER_FAILURE';

const CONNECT_VK_APPS_USER_REQUEST = 'api/CONNECT_VK_APPS_USER_REQUEST';
const CONNECT_VK_APPS_USER_SUCCESS = 'api/CONNECT_VK_APPS_USER_SUCCESS';
const CONNECT_VK_APPS_USER_FAILURE = 'api/CONNECT_VK_APPS_USER_FAILURE';

export const vkAppsUsersConstants = {
  CREATE_VK_APPS_USER_REQUEST,
  CREATE_VK_APPS_USER_SUCCESS,
  CREATE_VK_APPS_USER_FAILURE,

  GET_VK_APPS_USER_REQUEST,
  GET_VK_APPS_USER_SUCCESS,
  GET_VK_APPS_USER_FAILURE,

  DELETE_VK_APPS_USER_REQUEST,
  DELETE_VK_APPS_USER_SUCCESS,
  DELETE_VK_APPS_USER_FAILURE,

  CONNECT_VK_APPS_USER_REQUEST,
  CONNECT_VK_APPS_USER_SUCCESS,
  CONNECT_VK_APPS_USER_FAILURE,
};
