# Generated by Django 2.1.7 on 2019-02-20 00:10

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190202_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=100, verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.TextField(blank=True, max_length=50, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.TextField(blank=True, max_length=50, verbose_name='district'),
        ),
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.TextField(blank=True, max_length=100, verbose_name='education'),
        ),
        migrations.AlterField(
            model_name='user',
            name='experience',
            field=models.TextField(blank=True, max_length=100, verbose_name='experience'),
        ),
        migrations.AlterField(
            model_name='user',
            name='metro_station',
            field=models.TextField(blank=True, max_length=50, verbose_name='metro station'),
        ),
        migrations.AlterField(
            model_name='user',
            name='street',
            field=models.TextField(blank=True, max_length=50, verbose_name='street'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid value: minimum length is 3, maximum length is 30, alphanumeric characters, _, @, +, - are allowed', regex=re.compile('^[\\w.@+-]{3,30}$'))], verbose_name='username'),
        ),
    ]
