# Generated by Django 2.1.7 on 2019-03-10 15:06

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=100, validators=[utils.validators.NoSpecialSymbolsValidator()], verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.TextField(blank=True, max_length=50, validators=[utils.validators.NoSpecialSymbolsValidator()], verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.TextField(blank=True, max_length=50, validators=[utils.validators.NoSpecialSymbolsValidator()], verbose_name='district'),
        ),
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.TextField(blank=True, max_length=100, validators=[utils.validators.NoSpecialSymbolsValidator()], verbose_name='education'),
        ),
        migrations.AlterField(
            model_name='user',
            name='experience',
            field=models.TextField(blank=True, max_length=100, validators=[utils.validators.NoSpecialSymbolsValidator()], verbose_name='experience'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Anonymous', max_length=30, validators=[utils.validators.NoSpecialSymbolsValidator()], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Anonymous', max_length=30, validators=[utils.validators.NoSpecialSymbolsValidator()], verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='metro_station',
            field=models.TextField(blank=True, max_length=50, validators=[utils.validators.NoSpecialSymbolsValidator()], verbose_name='metro station'),
        ),
        migrations.AlterField(
            model_name='user',
            name='street',
            field=models.TextField(blank=True, max_length=50, validators=[utils.validators.NoSpecialSymbolsValidator()], verbose_name='street'),
        ),
    ]
