# Generated by Django 2.1.7 on 2019-03-14 02:38

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190310_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/', validators=[users.validators.validate_file_max_size], verbose_name='avatar'),
        ),
    ]
