# Generated by Django 2.1.7 on 2019-03-17 12:14

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190314_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Anonymous', max_length=30, validators=[utils.validators.AlphabetSymbolsValidator()], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Anonymous', max_length=30, validators=[utils.validators.AlphabetSymbolsValidator()], verbose_name='last name'),
        ),
    ]
