# Generated by Django 2.1.7 on 2019-04-04 17:09

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190317_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=400, validators=[utils.validators.NoSpecialSymbolsValidator()], verbose_name='bio'),
        ),
    ]
