# Generated by Django 2.1.7 on 2019-04-09 13:09

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190404_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=400, validators=[utils.validators.NoSpecialSymbolsValidator(), utils.validators.validate_profanity], verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.TextField(blank=True, max_length=50, validators=[utils.validators.NoSpecialSymbolsValidator(), utils.validators.validate_profanity], verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.TextField(blank=True, max_length=50, validators=[utils.validators.NoSpecialSymbolsValidator(), utils.validators.validate_profanity], verbose_name='district'),
        ),
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.TextField(blank=True, max_length=100, validators=[utils.validators.NoSpecialSymbolsValidator(), utils.validators.validate_profanity], verbose_name='education'),
        ),
        migrations.AlterField(
            model_name='user',
            name='experience',
            field=models.TextField(blank=True, max_length=100, validators=[utils.validators.NoSpecialSymbolsValidator(), utils.validators.validate_profanity], verbose_name='experience'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Anonymous', max_length=30, validators=[utils.validators.AlphabetSymbolsValidator(), utils.validators.validate_profanity], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Anonymous', max_length=30, validators=[utils.validators.AlphabetSymbolsValidator(), utils.validators.validate_profanity], verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='metro_station',
            field=models.TextField(blank=True, max_length=50, validators=[utils.validators.NoSpecialSymbolsValidator(), utils.validators.validate_profanity], verbose_name='metro station'),
        ),
        migrations.AlterField(
            model_name='user',
            name='street',
            field=models.TextField(blank=True, max_length=50, validators=[utils.validators.NoSpecialSymbolsValidator(), utils.validators.validate_profanity], verbose_name='street'),
        ),
    ]
