# Generated by Django 2.2a1 on 2019-02-06 01:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutors', '0002_auto_20190128_1553'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentrequest',
            unique_together={('student', 'tutor')},
        ),
    ]
