# Generated by Django 2.2a1 on 2019-02-10 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0003_auto_20190206_0138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentrequest',
            options={'verbose_name': 'Student Request', 'verbose_name_plural': 'Student Requests'},
        ),
        migrations.AlterModelOptions(
            name='tutorstudents',
            options={'verbose_name': "Tutor's Students", 'verbose_name_plural': "Tutors' Students"},
        ),
    ]
