# Generated by Django 2.1.7 on 2019-02-22 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0004_auto_20190210_0027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentrequest',
            options={'verbose_name': 'student request', 'verbose_name_plural': 'students requests'},
        ),
        migrations.AlterModelOptions(
            name='tutorstudents',
            options={'verbose_name': "tutor's students", 'verbose_name_plural': "tutors' students"},
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_request_student', to=settings.AUTH_USER_MODEL, verbose_name='student'),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_request_tutor', to=settings.AUTH_USER_MODEL, verbose_name='tutor'),
        ),
        migrations.AlterField(
            model_name='tutorstudents',
            name='students',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='students'),
        ),
        migrations.AlterField(
            model_name='tutorstudents',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='students_tutor', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
